#!/usr/bin/env python3
"""
memory-write.py — Skill wrapper for writing to the ETUS PMDocs memory system.

Called by skills (via Bash tool) when they detect a decision, preference,
pattern, or linear mapping during a session. Inserts into SQLite and
regenerates the corresponding markdown view.

Usage:
  python3 .claude/hooks/memory-write.py decision  "<text>" "<rationale>" "<skill>" "<phase>" "<tag1,tag2>"
  python3 .claude/hooks/memory-write.py preference "<text>" "<skill>" "<category>"
  python3 .claude/hooks/memory-write.py pattern    "<text>" "<skill>" "<applies_to>"
  python3 .claude/hooks/memory-write.py linear     "<etus_id>" "<linear_id>" "<title>" "<type>" "<status>"
  python3 .claude/hooks/memory-write.py supersede  "<DEC-NNN>" "<reason>"
  python3 .claude/hooks/memory-write.py query      <decisions|preferences|patterns|linear> [--phase <phase>] [--tag <tag>]

Exit codes:
  0 — success
  1 — usage error (wrong args)
  2 — DB error
"""

import sqlite3
import os
import sys
import json
import re
import tempfile
import traceback
from datetime import datetime, timezone
from path_utils import resolve_memory_dir
from state_utils import find_single_project_slug, sync_linear_mapping

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────
import hashlib as _hashlib

PROJECT_ROOT  = os.getcwd()
MEMORY_DIR    = resolve_memory_dir(PROJECT_ROOT)   # markdown views

# SQLite DB lives on the LOCAL filesystem (not virtiofs/FUSE, which blocks file locking).
_project_hash = _hashlib.md5(PROJECT_ROOT.encode()).hexdigest()[:8]
LOCAL_DB_DIR  = os.path.expanduser("~/.claude/etus-memory")
DB_PATH       = os.path.join(LOCAL_DB_DIR, f"memory-{_project_hash}.db")

HELP = """
memory-write.py — ETUS PMDocs memory writer

Commands:
  decision  <text> <rationale> <skill> <phase> <tags>
      Log a decision made by the user.
      <tags>: comma-separated, e.g. "tech-stack,frontend"

  preference <text> <skill> <category>
      Save a user preference.
      <category>: docs | naming | style | process | other

  pattern <text> <skill> <applies_to>
      Save a recurring pattern.
      <applies_to>: all | discovery | planning | design | implementation | feature | bug | spike

  linear <etus_id> <linear_id> <title> <type> <status>
      Map an ETUS ID to a Linear issue ID.
      <type>: story | task | bug | feature

  supersede <DEC-NNN> <reason>
      Mark a decision as superseded (by a new decision).

  query <decisions|preferences|patterns|linear|repo-docs> [--phase <p>] [--tag <t>]
      Query memory and print results (for skill context loading).

  index-docs
      Scan all docs/ for .md files and index them into the memory system.
      Equivalent to running memory-init.py --migrate but without resetting the DB.

Examples:
  python3 .claude/hooks/memory-write.py decision "Use React for frontend" "Team expertise" "project-context" "discovery" "tech-stack,frontend"
  python3 .claude/hooks/memory-write.py preference "Prefer concise docs without boilerplate" "project-context" "docs"
  python3 .claude/hooks/memory-write.py pattern "Always include a traceability section" "prd" "all"
  python3 .claude/hooks/memory-write.py linear "US-001" "LIN-123" "User can log in" "story" "in-progress"
  python3 .claude/hooks/memory-write.py supersede "DEC-002" "Switched from React to Vue after team change"
  python3 .claude/hooks/memory-write.py query decisions --phase discovery
"""


# ─────────────────────────────────────────────────────────────────────────────
# DB connection helpers
# ─────────────────────────────────────────────────────────────────────────────
def get_conn():
    if not os.path.exists(DB_PATH):
        print(f"[memory-write] ERROR: memory.db not found at {DB_PATH}", file=sys.stderr)
        print(f"[memory-write] DB location: {LOCAL_DB_DIR}", file=sys.stderr)
        print("[memory-write] Run: python3 .claude/hooks/memory-init.py", file=sys.stderr)
        sys.exit(2)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


# ─────────────────────────────────────────────────────────────────────────────
# View renderers (imported inline to avoid import dependency)
# ─────────────────────────────────────────────────────────────────────────────
def render_decisions(conn) -> str:
    rows = conn.execute(
        "SELECT id, decision, rationale, source_skill, phase, tags, status, created_at FROM decisions ORDER BY created_at DESC"
    ).fetchall()
    lines  = "# Decisions Log\n"
    lines += "<!-- AUTO-GENERATED by memory-write.py — do not edit directly. Source of truth: memory.db -->\n\n"
    lines += "Decisions made during this project. Skills should NOT re-question these unless the user explicitly asks to revisit.\n\n"
    lines += "## How to use\n"
    lines += "- Before proposing approaches, check if a relevant decision already exists here\n"
    lines += "- If it does, state \"We previously decided [X] because [Y]\" and proceed\n"
    lines += "- Only add new decisions when the user makes a choice between approaches\n\n"
    lines += "## Decisions\n\n"
    if not rows:
        lines += "(none yet — decisions will be logged as the project progresses)\n"
    else:
        for r in rows:
            tags     = json.loads(r["tags"]) if r["tags"] else []
            tags_str = f" `{'` `'.join(tags)}`" if tags else ""
            status   = r["status"]
            status_icon = "✅" if status == "active" else ("⚠️ superseded" if status == "superseded" else "❌ revoked")
            lines += f"### DEC-{r['id']:03d} — {r['decision']}\n"
            lines += f"- **Rationale:** {r['rationale'] or '—'}\n"
            lines += f"- **Source:** {r['source_skill'] or '—'} | **Phase:** {r['phase'] or '—'}{tags_str}\n"
            lines += f"- **Status:** {status_icon} | **Logged:** {r['created_at'][:10]}\n\n"
    return lines


def render_preferences(conn) -> str:
    rows = conn.execute(
        "SELECT id, preference, source_skill, category, created_at FROM preferences ORDER BY category, created_at DESC"
    ).fetchall()
    lines  = "# User & Team Preferences\n"
    lines += "<!-- AUTO-GENERATED by memory-write.py — do not edit directly. Source of truth: memory.db -->\n\n"
    lines += "Preferences discovered during interactions. Skills should apply these automatically without re-asking.\n\n"
    lines += "## How to use\n"
    lines += "- Read this file at the start of every skill\n"
    lines += "- Apply preferences silently (don't announce \"I see you prefer X\")\n"
    lines += "- Add new preferences when the user expresses a clear preference\n\n"
    lines += "## Preferences\n\n"
    if not rows:
        lines += "(none yet — preferences will be captured as the project progresses)\n"
    else:
        by_cat = {}
        for r in rows:
            cat = r["category"] or "other"
            by_cat.setdefault(cat, []).append(r)
        for cat, items in sorted(by_cat.items()):
            lines += f"### {cat.capitalize()}\n\n"
            for r in items:
                lines += f"- **PREF-{r['id']:03d}:** {r['preference']} _(from {r['source_skill'] or '—'}, {r['created_at'][:10]})_\n"
            lines += "\n"
    return lines


def render_patterns(conn) -> str:
    rows = conn.execute(
        "SELECT id, pattern, source_skill, applies_to, created_at FROM patterns ORDER BY created_at DESC"
    ).fetchall()
    lines  = "# Project Patterns\n"
    lines += "<!-- AUTO-GENERATED by memory-write.py — do not edit directly. Source of truth: memory.db -->\n\n"
    lines += "Patterns discovered during this project that should be applied consistently across all documents.\n\n"
    lines += "## How to use\n"
    lines += "- Read this file when generating any document\n"
    lines += "- Apply patterns automatically\n"
    lines += "- Add new patterns when recurring needs are identified\n\n"
    lines += "## Patterns\n\n"
    if not rows:
        lines += "(none yet — patterns will emerge as documents are created)\n"
    else:
        for r in rows:
            lines += f"### PAT-{r['id']:03d} — applies to: `{r['applies_to']}`\n"
            lines += f"{r['pattern']}\n"
            lines += f"_(from {r['source_skill'] or '—'}, {r['created_at'][:10]})_\n\n"
    return lines


def render_linear_mapping(conn) -> str:
    rows = conn.execute(
        "SELECT etus_id, linear_id, title, type, status, updated_at FROM linear_mapping ORDER BY etus_id"
    ).fetchall()
    lines  = "# Linear Issue Mapping\n"
    lines += "<!-- AUTO-GENERATED by memory-write.py — do not edit directly. Source of truth: memory.db -->\n\n"
    lines += "Mapping between ETUS document IDs and Linear issue IDs. Maintained automatically by skills with LINEAR SYNC.\n\n"
    lines += "| ETUS ID | Linear ID | Title | Type | Status | Updated |\n"
    lines += "|---------|-----------|-------|------|--------|----------|\n"
    if not rows:
        lines += "\n_(No mappings yet — will be populated during planning and implementation phases)_\n"
    else:
        for r in rows:
            lines += f"| {r['etus_id']} | {r['linear_id']} | {r['title'] or '—'} | {r['type'] or '—'} | {r['status'] or '—'} | {r['updated_at'][:10]} |\n"
    return lines


def save_view(filename: str, content: str):
    os.makedirs(MEMORY_DIR, exist_ok=True)
    path = os.path.join(MEMORY_DIR, filename)
    fd, tmp_path = tempfile.mkstemp(
        dir=os.path.dirname(path),
        prefix=".tmp_",
        suffix=os.path.splitext(path)[1],
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


# ─────────────────────────────────────────────────────────────────────────────
# Commands
# ─────────────────────────────────────────────────────────────────────────────
def cmd_decision(args):
    if len(args) < 2:
        print("Usage: decision <text> [<rationale>] [<skill>] [<phase>] [<tags>]", file=sys.stderr)
        sys.exit(1)
    text      = args[0]
    rationale = args[1] if len(args) > 1 else ""
    skill     = args[2] if len(args) > 2 else ""
    phase     = args[3] if len(args) > 3 else ""
    tags_raw  = args[4] if len(args) > 4 else ""
    tags      = json.dumps([t.strip() for t in tags_raw.split(",") if t.strip()])
    now       = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    conn = get_conn()
    conn.execute(
        "INSERT INTO decisions (decision, rationale, source_skill, phase, tags, status, created_at) VALUES (?,?,?,?,?,'active',?)",
        (text, rationale, skill, phase, tags, now)
    )
    row_id = conn.execute("SELECT last_insert_rowid() as id").fetchone()["id"]
    try:
        save_view("decisions.md", render_decisions(conn))
    except Exception:
        conn.rollback()
        raise
    conn.commit()
    conn.close()
    print(f"✓ Decision logged: DEC-{row_id:03d} — {text}")


def cmd_preference(args):
    if len(args) < 1:
        print("Usage: preference <text> [<skill>] [<category>]", file=sys.stderr)
        sys.exit(1)
    text     = args[0]
    skill    = args[1] if len(args) > 1 else ""
    category = args[2] if len(args) > 2 else "other"
    now      = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    conn = get_conn()
    conn.execute(
        "INSERT INTO preferences (preference, source_skill, category, created_at) VALUES (?,?,?,?)",
        (text, skill, category, now)
    )
    row_id = conn.execute("SELECT last_insert_rowid() as id").fetchone()["id"]
    try:
        save_view("preferences.md", render_preferences(conn))
    except Exception:
        conn.rollback()
        raise
    conn.commit()
    conn.close()
    print(f"✓ Preference saved: PREF-{row_id:03d} — {text}")


def cmd_pattern(args):
    if len(args) < 1:
        print("Usage: pattern <text> [<skill>] [<applies_to>]", file=sys.stderr)
        sys.exit(1)
    text       = args[0]
    skill      = args[1] if len(args) > 1 else ""
    applies_to = args[2] if len(args) > 2 else "all"
    now        = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    conn = get_conn()
    conn.execute(
        "INSERT INTO patterns (pattern, source_skill, applies_to, created_at) VALUES (?,?,?,?)",
        (text, skill, applies_to, now)
    )
    row_id = conn.execute("SELECT last_insert_rowid() as id").fetchone()["id"]
    try:
        save_view("patterns.md", render_patterns(conn))
    except Exception:
        conn.rollback()
        raise
    conn.commit()
    conn.close()
    print(f"✓ Pattern saved: PAT-{row_id:03d} — applies to: {applies_to}")


def cmd_linear(args):
    if len(args) < 2:
        print("Usage: linear <etus_id> <linear_id> [<title>] [<type>] [<status>]", file=sys.stderr)
        sys.exit(1)
    etus_id   = args[0]
    linear_id = args[1]
    title     = args[2] if len(args) > 2 else ""
    ltype     = args[3] if len(args) > 3 else ""
    status    = args[4] if len(args) > 4 else "todo"
    now       = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    conn = get_conn()
    conn.execute("""
        INSERT INTO linear_mapping (etus_id, linear_id, title, type, status, created_at, updated_at)
        VALUES (?,?,?,?,?,?,?)
        ON CONFLICT(etus_id) DO UPDATE SET
            linear_id  = excluded.linear_id,
            title      = excluded.title,
            type       = excluded.type,
            status     = excluded.status,
            updated_at = excluded.updated_at
    """, (etus_id, linear_id, title, ltype, status, now, now))
    try:
        save_view("linear-mapping.md", render_linear_mapping(conn))
    except Exception:
        conn.rollback()
        raise
    conn.commit()
    conn.close()

    local_sync_note = ""
    project_slug = find_single_project_slug(PROJECT_ROOT)
    if project_slug:
        try:
            sync_path = sync_linear_mapping(
                PROJECT_ROOT,
                project_slug,
                etus_id,
                linear_id,
                title=title,
                item_type=ltype,
                status=status,
            )
            local_sync_note = f" | local sync: {sync_path}"
        except Exception as exc:
            local_sync_note = f" | local sync skipped: {type(exc).__name__}"

    print(f"✓ Linear mapping saved: {etus_id} → {linear_id}{local_sync_note}")


def cmd_supersede(args):
    if len(args) < 1:
        print("Usage: supersede <DEC-NNN> [<reason>]", file=sys.stderr)
        sys.exit(1)
    dec_ref = args[0]
    reason  = args[1] if len(args) > 1 else "superseded"
    # Extract numeric ID
    match = re.search(r"(\d+)", dec_ref)
    if not match:
        print(f"[memory-write] ERROR: Could not parse decision ID from '{dec_ref}'", file=sys.stderr)
        sys.exit(1)
    dec_id = int(match.group(1))

    conn = get_conn()
    row = conn.execute("SELECT id FROM decisions WHERE id=?", (dec_id,)).fetchone()
    if not row:
        print(f"[memory-write] ERROR: Decision DEC-{dec_id:03d} not found", file=sys.stderr)
        conn.close()
        sys.exit(1)
    conn.execute("UPDATE decisions SET status='superseded', rationale=COALESCE(rationale,'')||' [Superseded: '||?||']' WHERE id=?",
                 (reason, dec_id))
    try:
        save_view("decisions.md", render_decisions(conn))
    except Exception:
        conn.rollback()
        raise
    conn.commit()
    conn.close()
    print(f"✓ Decision DEC-{dec_id:03d} marked as superseded: {reason}")


def cmd_query(args):
    if not args:
        print("Usage: query <decisions|preferences|patterns|linear> [--phase <p>] [--tag <t>]", file=sys.stderr)
        sys.exit(1)

    table    = args[0]
    phase    = None
    tag      = None
    i = 1
    while i < len(args):
        if args[i] == "--phase" and i + 1 < len(args):
            phase = args[i + 1]; i += 2
        elif args[i] == "--tag" and i + 1 < len(args):
            tag = args[i + 1]; i += 2
        else:
            i += 1

    conn = get_conn()

    if table == "decisions":
        q = "SELECT id, decision, rationale, phase, tags, status FROM decisions WHERE 1=1"
        params = []
        if phase:
            q += " AND phase=?"; params.append(phase)
        if tag:
            q += " AND tags LIKE ?"; params.append(f'%"{tag}"%')
        q += " AND status='active' ORDER BY created_at DESC"
        rows = conn.execute(q, params).fetchall()
        if not rows:
            print("(no decisions found)")
        else:
            for r in rows:
                tags = ", ".join(json.loads(r["tags"])) if r["tags"] else ""
                print(f"DEC-{r['id']:03d} [{r['phase'] or '—'}] {r['decision']}")
                if r["rationale"]:
                    print(f"         → {r['rationale']}")
                if tags:
                    print(f"         tags: {tags}")

    elif table == "preferences":
        rows = conn.execute("SELECT id, preference, category FROM preferences ORDER BY category").fetchall()
        if not rows:
            print("(no preferences found)")
        else:
            for r in rows:
                print(f"PREF-{r['id']:03d} [{r['category'] or '—'}] {r['preference']}")

    elif table == "patterns":
        rows = conn.execute("SELECT id, pattern, applies_to FROM patterns ORDER BY created_at DESC").fetchall()
        if not rows:
            print("(no patterns found)")
        else:
            for r in rows:
                print(f"PAT-{r['id']:03d} [applies to: {r['applies_to']}] {r['pattern']}")

    elif table == "linear":
        rows = conn.execute("SELECT etus_id, linear_id, title, status FROM linear_mapping ORDER BY etus_id").fetchall()
        if not rows:
            print("(no linear mappings found)")
        else:
            for r in rows:
                print(f"{r['etus_id']} → {r['linear_id']}  [{r['status']}]  {r['title'] or ''}")

    elif table == "repo-docs":
        rows = conn.execute(
            "SELECT path, doc_type, status, updated_at FROM documents WHERE mode='reference' ORDER BY doc_type, path"
        ).fetchall()
        if not rows:
            print("(no repo docs indexed)")
        else:
            for r in rows:
                print(f"[{r['doc_type']}] {r['path']}  ({r['status']}, {r['updated_at'][:10]})")

    else:
        print(f"Unknown table: {table}. Choose: decisions, preferences, patterns, linear, repo-docs", file=sys.stderr)
        sys.exit(1)

    conn.close()


def cmd_index_docs(args):
    """Scan docs/ for .md files and index them into the memory system."""
    import importlib.util

    init_script = os.path.join(PROJECT_ROOT, ".claude/hooks/memory-init.py")
    if not os.path.exists(init_script):
        print("[memory-write] ERROR: memory-init.py not found", file=sys.stderr)
        sys.exit(2)

    spec = importlib.util.spec_from_file_location("memory_init", init_script)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    conn = get_conn()
    n = mod.migrate_existing_docs(conn)
    print(f"✓ Indexed {n} documents from docs/")

    # Regenerate all views
    mod.MEMORY_DIR = MEMORY_DIR  # ensure it uses our MEMORY_DIR
    mod.regenerate_all_views(conn)
    print("✓ All memory views regenerated (including repo-docs.md)")
    conn.close()


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────
def main():
    args = sys.argv[1:]

    if not args or args[0] in ("-h", "--help"):
        print(HELP)
        sys.exit(0)

    command = args[0].lower()
    rest    = args[1:]

    dispatch = {
        "decision":    cmd_decision,
        "preference":  cmd_preference,
        "pattern":     cmd_pattern,
        "linear":      cmd_linear,
        "supersede":   cmd_supersede,
        "query":       cmd_query,
        "index-docs":  cmd_index_docs,
    }

    if command not in dispatch:
        print(f"Unknown command: {command}", file=sys.stderr)
        print(f"Available: {', '.join(dispatch.keys())}", file=sys.stderr)
        sys.exit(1)

    try:
        dispatch[command](rest)
    except SystemExit:
        raise
    except Exception as e:
        print(f"[memory-write] ERROR: {e}", file=sys.stderr)
        print(traceback.format_exc(), file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
